version: '3'
services:
  web:
    image: nginx:1.17.5
    restart: always
    networks:
      - "default"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
      - "8100:80"
networks:
  default:
    driver: "bridge"
